# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-theme-altinn"
license = "MIT"
licenselink = "https://github.com/Altinn/hugo-theme-altinn/blob/master/LICENSE.md"
description = "Altinn Documentation theme for Hugo"
homepage = "https://github.com/Altinn/hugo-theme-altinn"
repo = "https://github.com/Altinn/hugo-theme-altinn"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.25

[author]
  name = "Altinn"
  homepage = "https://altinn.no"

[original]
  name = "Docdock"
  homepage = "https://docdock.netlify.com/"
  repo = "https://github.com/vjeantet/hugo-theme-docdock"
  licenselink = "https://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"