{
  "openapi": "3.0.1",
  "info": {
    "title": "Altinn.AccessManagement.Api.Enduser | v1",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://platform.tt02.altinn.no/accessmanagement/api/v1",
      "description": "Integration Test"
    },
    {
      "url": "https://platform.altinn.no/accessmanagement/api/v1",
      "description": "Production"
    }
  ],
  "paths": {
    "/enduser/authorizedparties": {
      "get": {
        "tags": [
          "AuthorizedParties"
        ],
        "security": [
          {
            "oauth2": [
              "EnduserAuthorizedParty"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/my/clients": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/my/clientproviders": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/clients": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/accesspackages": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/clients/accesspackages": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      }
    },
    "/enduser/connections": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_BIDIRECTIONAL",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/users": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "InstanceDelegation"
            ]
          }
        ]
      }
    },
    "/enduser/connections/accesspackages": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_BIDIRECTIONAL",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/accesspackages/delegationcheck": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/roles": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_BIDIRECTIONAL",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/rights": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/delegationcheck": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/instances": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_BIDIRECTIONAL",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/instances/rights": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_CONDITIONAL_BIDRECTIONAL",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "InstanceDelegation"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/instances/delegationcheck": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "InstanceDelegation"
            ]
          }
        ]
      }
    },
    "/enduser/connections/resources/instances/users": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_CONNECTIONS_WRITE_TOOTHERS",
              "InstanceDelegation"
            ]
          }
        ]
      }
    },
    "/enduser/request": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_READ",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/request/draft": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:portal/enduser"
            ]
          }
        ]
      }
    },
    "/enduser/request/draft/confirm": {
      "put": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/request/sent": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_READ",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/request/sent/count": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_READ",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/request/sent/withdraw": {
      "put": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/request/received": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_READ",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/request/received/count": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_READ",
              "AccessManagementEndUserRead"
            ]
          }
        ]
      }
    },
    "/enduser/request/received/approve": {
      "put": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/request/received/reject": {
      "put": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/request/resource": {
      "post": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    },
    "/enduser/request/package": {
      "post": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "POLICY_ENDUSER_REQUESTS_WRITE",
              "AccessManagementEndUserWrite"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "apiKey",
        "description": "Standard Authorization header using the Bearer scheme. Example: \"bearer {token}\"",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}