{
  "openapi": "3.0.4",
  "info": {
    "title": "Altinn.AccessManagement.Api.Enduser",
    "version": "2.0"
  },
  "servers": [
    {
      "url": "https://platform.tt02.altinn.no/accessmanagement/api/v2",
      "description": "Integration Test"
    },
    {
      "url": "https://platform.altinn.no/accessmanagement/api/v2",
      "description": "Production"
    }
  ],
  "paths": {
    "/enduser/clientdelegations/my/clients": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/my/clientproviders": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/my/clients/accesspackages/delete": {
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/my/clients/resources/delete": {
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations/myclients.write"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/clients": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/clients": {
      "delete": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/accesspackages": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/clients/accesspackages": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/accesspackages/delete": {
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/resources": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/clients/resources": {
      "get": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.read",
              "CLIENTDELEGATION_READ"
            ]
          }
        ]
      }
    },
    "/enduser/clientdelegations/agents/resources/delete": {
      "post": {
        "tags": [
          "Client Delegation"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:clientdelegations.write",
              "CLIENTDELEGATION_WRITE"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "http",
        "description": "Standard Authorization header using the Bearer scheme. Example: \"bearer {token}\"",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}