{
  "openapi": "3.0.4",
  "info": {
    "title": "Altinn.AccessManagement.Api.ServiceOwner",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://platform.tt02.altinn.no/accessmanagement/api/v1",
      "description": "Integration Test"
    },
    {
      "url": "https://platform.altinn.no/accessmanagement/api/v1",
      "description": "Production"
    }
  ],
  "paths": {
    "/serviceowner/connections/accesspackages": {
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegations:accesspackage.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/connections/accesspackages/revoke": {
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegations:accesspackage.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/connections/resources/rights": {
      "get": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegations:resource.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/connections/resources": {
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegations:resource.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/connections/resources/revoke": {
      "post": {
        "tags": [
          "Connections"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegations:resource.write"
            ]
          }
        ]
      }
    },
    "/maskinporten/delegations": {
      "get": {
        "tags": [
          "MaskinportenDelegations"
        ],
        "security": [
          {
            "oauth2": [
              "MaskinportenDelegationsProxy"
            ]
          }
        ]
      }
    },
    "/serviceowner/delegationrequests/_meta/urns/party": {
      "get": {
        "tags": [
          "Request"
        ]
      }
    },
    "/serviceowner/delegationrequests/{id}/status": {
      "get": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegationrequests.read"
            ]
          }
        ]
      }
    },
    "/serviceowner/delegationrequests/{id}/withdraw": {
      "put": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegationrequests.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/delegationrequests/resource": {
      "post": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegationrequests.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/delegationrequests/package": {
      "post": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegationrequests.write"
            ]
          }
        ]
      }
    },
    "/serviceowner/delegationrequests": {
      "post": {
        "tags": [
          "Request"
        ],
        "security": [
          {
            "oauth2": [
              "altinn:serviceowner/delegationrequests.write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "http",
        "description": "Standard Authorization header using the Bearer scheme. Example: \"bearer {token}\"",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}