name: 'Close stale and lock closed issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
permissions:
  contents: read
jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@08e671be8ac8944d0e132aa71d0ae8ccfb347675
        with:
          issue-inactive-days: 21
          add-issue-labels: 'Outdated'
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          pr-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
      - uses: actions/stale@04a1828bc18ada028d85a0252a47cd2963a91abe
        with:
          operations-per-run: 999
          days-before-issue-stale: 365
          days-before-pr-stale: 365
          days-before-issue-close: 56
          days-before-pr-close: 56
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. The resources of the Hugo team are limited, and so we are asking for your help.

            If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

            If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

            This issue will automatically be closed in the near future if no further activity occurs. Thank you for all your contributions.
          stale-pr-message: This PR has been automatically marked as stale because it has not had
            recent activity. The resources of the Hugo team are limited, and so we are asking for your help.

            Please check https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#code-contribution and verify that this code contribution fits with the description. If yes, tell is in a comment.

            This PR will automatically be closed in the near future if no further activity occurs. Thank you for all your contributions.
          stale-issue-label: 'Stale'
          exempt-issue-labels: 'Keep,Security'
          stale-pr-label: 'Stale'
          exempt-pr-labels: 'Keep,Security'
