name: Hugo Verifications

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    name: Build and Check links
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: '0.162.0'
          extended: true 

      - name: Build
        run: hugo

      - name: Build pagefind index
        run: npx -y pagefind --site "public"

      - name: Verify links
        uses: untitaker/hyperlink@9375bc4063712ad490d5eb3d54df0b6aade15e54 # 0.3.2
        with:
          args: public/ --check-anchors --sources content/
